[workspace]
authors = ["Tyler Jost <tjost@bwh.harvard.edu>"]
channels = ["conda-forge"]
name = "labLedger"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[tasks]

[dependencies]
transformers = ">=4.56.2,<5"
pytorch-gpu = "*"
